modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Team-Fruit/SaveTools/issues"

[[mods]]
modId="savetools"
version="${file.jarVersion}"
displayName="SaveTools"
displayURL="https://www.teamfruit.net/"
authors="sjcl"
description='''
This mod protects your preciousfully tools/weapons from breaking via over use!!
'''

[[dependencies.savetools]]
    modId="cloth-config2"
    mandatory=true
    versionRange="[3.0,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.savetools]] #optional
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.savetools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="CLIENT"