modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/Team-Fruit/SaveTools/issues"

[[mods]]
modId="savetools"
version="${file.jarVersion}"
displayName="SaveTools"
displayURL="https://www.teamfruit.net/"
logoFile="savetools.png"
authors="sjcl"
description='''
This mod protects your preciousfully tools/weapons from breaking via over use!!
'''

[[dependencies.savetools]]
    modId="forge"
    mandatory=true
    versionRange="[25.0.210,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.savetools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="CLIENT"